// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwh-nbbL63fr6DKRGY_Ifts8vtdOiJK-Y',
    appId: '1:927716536503:web:3e0a8feb3dabbd143a1d32',
    messagingSenderId: '927716536503',
    projectId: 'veltrik-vinal-version',
    authDomain: 'veltrik-vinal-version.firebaseapp.com',
    storageBucket: 'veltrik-vinal-version.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6SJJFmXCHinWu347xDFhT57RjkW4e_30',
    appId: '1:927716536503:android:84d63cf75015b0503a1d32',
    messagingSenderId: '927716536503',
    projectId: 'veltrik-vinal-version',
    storageBucket: 'veltrik-vinal-version.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEsCYAXzyc73RkpcTB0X-_wWkE0WJNzHI',
    appId: '1:927716536503:ios:36515210d27538463a1d32',
    messagingSenderId: '927716536503',
    projectId: 'veltrik-vinal-version',
    storageBucket: 'veltrik-vinal-version.firebasestorage.app',
    iosBundleId: 'com.veltrik.veltrik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEsCYAXzyc73RkpcTB0X-_wWkE0WJNzHI',
    appId: '1:927716536503:ios:36515210d27538463a1d32',
    messagingSenderId: '927716536503',
    projectId: 'veltrik-vinal-version',
    storageBucket: 'veltrik-vinal-version.firebasestorage.app',
    iosBundleId: 'com.veltrik.veltrik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwh-nbbL63fr6DKRGY_Ifts8vtdOiJK-Y',
    appId: '1:927716536503:web:d0e1e96419802ac93a1d32',
    messagingSenderId: '927716536503',
    projectId: 'veltrik-vinal-version',
    authDomain: 'veltrik-vinal-version.firebaseapp.com',
    storageBucket: 'veltrik-vinal-version.firebasestorage.app',
  );
}
